logging:
  file:
    name: './rzub.log'
    max-history: 10
    max-size: 20MB
  level:
    ROOT: info
    com.github.rzub: debug
    io.github.sepgh: trace
rzub:
  conf:
    base: '.'
    settings: '${rzub.conf.base}/settings.json'
    access: '${rzub.conf.base}/access.json'
    alias: '${rzub.conf.base}/alias.json'
  bot:
    responses:
      - "I'm not your google assistance, please use valid commands to talk to me. try `!help` to see them."
      - "My developer is not smart enough to make me as smart as himself!  try `!help` to see commands I support."
      - "Ssshhh, just use my commands. (see `!help`)"
      - "Yes master?"
      - "I'm not as dumb as you think I would be. I can understand certain commands. Can you?"
      - "I'm only loyal to my creator mr **sep#8562** and my current owner! but I would care about what you say if you use valid commands from `!help`."
      - "Yes, hello?"
      - "Try `!help`. Thanks."
debug: false
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  discord:
    enabled: true
    guild-id: 745213074759352410
